packages:
  - 'apps/*'
  - 'libs/*'

# Catalog settings for improved dependency management
catalog:
  # Backend dependencies
  '@types/node': '^20.0.0'
  express: '^4.18.2'
  cors: '^2.8.5'
  helmet: '^7.0.0'
  compression: '^1.7.4'
  
  # Database & ORM
  '@prisma/client': '^5.0.0'
  prisma: '^5.0.0'
  
  # Authentication
  jsonwebtoken: '^9.0.1'
  bcryptjs: '^2.4.3'
  
  # Validation
  zod: '^3.21.4'
  
  # Frontend dependencies
  react: '^18.2.0'
  react-dom: '^18.2.0'
  next: '^13.4.0'
  
  # React Native
  react-native: '^0.72.0'
  '@react-navigation/native': '^6.1.7'
  '@react-navigation/stack': '^6.3.17'
  
  # State Management
  '@tanstack/react-query': '^4.29.0'
  zustand: '^4.3.9'
  
  # UI Components
  '@radix-ui/react-accordion': '^1.1.2'
  '@radix-ui/react-dialog': '^1.0.4'
  'react-native-paper': '^5.9.1'
  
  # Styling
  tailwindcss: '^3.3.0'
  '@tailwindcss/forms': '^0.5.4'
  '@tailwindcss/typography': '^0.5.9'
  
  # Development tools
  typescript: '^5.1.6'
  '@types/react': '^18.2.0'
  '@types/react-dom': '^18.2.0'
  eslint: '^8.45.0'
  prettier: '^3.0.0'
  jest: '^29.6.0'
  '@testing-library/react': '^13.4.0'