<p><strong>WISER CAPITAL SOLAR INTEGRATOR PLATFORM AND MARKETPLACE SEAT LICENSE AGREEMENT</strong></p>

<p>This&nbsp;<strong>Solar Integrator</strong>&nbsp;<strong>Platform and Marketplace Seat License Agreement</strong>&nbsp;(the &ldquo;License Agreement&rdquo;) entered into on the Effective Date by and between Wiser Capital, LLC, a California limited liability company, having its principal place of business at&nbsp;2020 Alameda Padre Serra, Suite 220, Santa Barbara, CA, 93103&nbsp;(&ldquo;Licensor&rdquo; or &ldquo;Wiser Capital&rdquo;) and the user of the Platform and corresponding Company (if any) on whose behalf the user is acting (the &ldquo;Licensee&rdquo; or &ldquo;you&rdquo;) who will be the user of Licensor&rsquo;s proprietary Platform and participant in Licensor&rsquo;s Marketplace.&nbsp;&nbsp;Licensor and License may be referred to herein as a &ldquo;Party&rdquo; and collectively as the &ldquo;Parties.&rdquo;</p>

<p><strong>RECITALS</strong></p>

<p>Licensor is the owner of a hosted software platform and related technology that allows end-users to enter data about, and participate in one or more phases of, a solar energy generation project (the &ldquo;Platform&rdquo;), wherein a Licensee may use the Platform to enter and track their own leads, economically model and optimize the size of these potential projects, generate proposals, and access project development and financing services, and to participate in a solar energy project marketplace to obtain leads, generate and submit proposals on leads provided by Wiser Capital, and perform one or more of the configuration, design, analysis, cost analysis, and investment analysis of such projects (the &ldquo;Marketplace&rdquo;)<strong>.&nbsp;</strong></p>

<p>Licensor is the owner of any Intellectual Property Rights (as defined herein) related to the Services, including the Platform and the Marketplace.</p>

<p>Licensor desires to provide a revocable, non-exclusive, non-transferable, non-sublicensable, limited license to Licensee to access and use the Platform for purposes related to Licensee&rsquo;s development of their own leads resulting in solar energy project development and the Licensee&rsquo;s participation in the Marketplace to source leads from Wiser Capital.</p>

<p>Licensee desires to obtain a revocable, non-exclusive, non-transferable, non-sublicensable, limited license to access and use the Platform for purposes related to the engineering, procurement, construction, transacting and financing of solar energy generation projects and to participate in the Marketplace.</p>

<p>LICENSEE AGREES TO BE BOUND BY THE TERMS OF THIS LICENSE AGREEMENT&nbsp;BY CLICKING THE &quot;I HAVE READ AND AGREE&quot; ICON DISPLAYED AS PART OF THE REGISTRATION PROCESS.&nbsp;&nbsp;&nbsp;IF LICENSEE DOES NOT AGREE TO THESE TERMS, THEN LICENSEE SHOULD NOT CLICK THE ICON AND LICENSEE SHALL HAVE NO ACCESS TO THE PLATFORM.</p>

<p><strong>NOW, THEREFORE,</strong>&nbsp;in consideration of the following mutual promises and other good and valuable consideration, the receipt and sufficiency of which is acknowledged, the Parties hereby agree as follows.</p>

<p><strong>1.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Definitions.&nbsp;&nbsp;</strong>As used in this License Agreement and in any Order Forms now or hereafter associated with Licensee&rsquo;s use of the Platform or participation in the Marketplace.&nbsp;</p>

<p><strong>a.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Company&rdquo; means the legal business entity that each User is acting on behalf of, through the use of the Platform and Marketplace, unless it can be shown by reliable evidence such User is acting in an individual capacity.&nbsp;</p>

<p><strong>b.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Content&quot; means any public or non-public information in any medium, data, and documents contained or made available to you in the course of your access and use of the Platform or your participation in the Marketplace.</p>

<p><strong>c.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Customer Data&quot; means any data, information or material provided or submitted by you to the Licensor in the course of using the Platform or participating in the Marketplace.</p>

<p><strong>d.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Direct Competitor&rdquo; means any person or entity that offers or provides either (i) software or information management services that are intended for use or are likely to be used by consumers, installers, developers or investors in solar energy systems or otherwise in connection with the installation of solar energy systems, or (ii) financing solutions for residential or commercial solar energy systems, including but not limited to loans, equipment leases or power purchase agreements.</p>

<p><strong>e.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Effective Date&quot; means the date you register with the Platform and accept this License Agreement by acknowledging your acceptance by clicking the &quot;I have read and agree&quot; icon presented on the screen during registration.&nbsp; Effective Date also indicates the start of the Trial Period unless or as otherwise modified by Licensor.</p>

<p><strong>f.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Host Facility&rdquo; means a specific physical address, owner, employees, associates or other party interested in using the Platform or Services to obtain information related to the installation, use and benefits of a solar energy generation system whether the system is purchased and owned by the Host Facility or purchased and owned by a &ldquo;third-party&rdquo; investor.</p>

<p><strong>g.&nbsp;&nbsp;&nbsp;</strong>&quot;Initial Term&quot; means the initial period during which you are obligated to pay for the Service.</p>

<p><strong>h.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Intellectual Property Rights&quot; means unpatented inventions, patent applications, patents, designs, copyrights, trademarks, service marks, trade names, domain name rights, mask work rights, software, source code, object code, processes, algorithms, know-how, knowledge, techniques, designs and other tangible or intangible developments and other trade secret rights, and all other intellectual property rights, derivatives thereof, and forms of protection of a similar nature anywhere in the world.</p>

<p><strong>i.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Lead&rdquo; means a Host Facility which has create its own Profile and entered its project information and is using the Platform and the Marketplace to utilize the Services to&nbsp;obtain proposals and/or construct a solar energy generation project.</p>

<p><strong>j.&nbsp;&nbsp;&nbsp;&nbsp;</strong>&ldquo;Licensee Lead&rdquo; means a host facility which Licensee has independently identified or engaged wherein the host facility is interested in having the Licensee layout, design, generate a proposal, and/or contract for the construction of a solar energy generation project.&nbsp; Licensee Lead does not include any Lead identified through Licensee&rsquo;s use of the Services. Licensee Lead only applies to individual Profile for a Host Facility entered into the Platform by Licensee, and does not mean that other Licensees may create a Profile using their Seat License that represents a distinct Licensee Lead to that Licensee.</p>

<p><strong>k.&nbsp;&nbsp;&nbsp;</strong>&quot;License Administrator(s)&quot; means those Users designated by you who are authorized to purchase licenses online using its Platform account or by executing written Order Forms and to create User accounts and otherwise administers your use of the Service.</p>

<p><strong>l.&nbsp;&nbsp;&nbsp;</strong>&quot;License Term(s)&quot; means the contract period during Users are licensed to use the Service pursuant to the Order Form(s), including a Trial Period, the Initial Term, and any Renewal Term.</p>

<p><strong>m.&nbsp;</strong>&quot;Order Form(s)&quot; means the form evidencing the initial subscription for the Service and any subsequent order forms submitted online or in written form, specifying, among other things, the number of licenses and other services contracted for, the applicable fees, the contract period, and other terms or charges as agreed to between the parties, each such Order Form to be incorporated into and to become a part of this Agreement (in the event of any conflict between the terms of this Agreement and the terms of any such Order Form, the terms of this Agreement will prevail).</p>

<p><strong>n.&nbsp;</strong>&ldquo;Profile&rdquo; means the unique identity in the Platform of a combination of data and information related to a Host Facility that together represents a potential project. Profiles are created either by Host Facilities, as Leads that may be presented in the Marketplace, or by one or more Licensees, as Licensee Leads, each of which represents a distinct Profile in the Platform. Multiple Profiles may exist for the same Host Facility and be differentiated by any one or more variations of data or parameters related to project specification and related economics. &nbsp;</p>

<p><strong>o.&nbsp; &nbsp;</strong>&ldquo;Renewal Term&rdquo; means any terms subsequent to the expiration of the Initial Term.</p>

<p><strong>p. &nbsp;</strong>&ldquo;Seat License&rdquo; means the right of one User to access and use the Services using a unique username and password assigned to such User.</p>

<p><strong>q.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Seat License&rdquo; means the right of one User to access and use the Services using a unique username and password assigned to such User.&nbsp;</p>

<p><strong>r.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;Service(s)&quot; means use of the current, post or future editions of the Platform, participation in the Marketplace, and any other services delivered on or off line related to your participation in the Marketplace or related to the engineering, procurement, construction, transacting and financing of a solar energy generation project.</p>

<p><strong>s.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Solar Integrator&rdquo; shall mean the engineering, procurement and construction provider of a solar energy generation project, or other entities, including component manufacturers, involved in or connected to the manufacturing, design, engineering, permitting, construction, commissioning, operations and/or maintenance of solar energy generating systems using the Platform to advance its involvement in the photovoltaic industry.</p>

<p><strong>t.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;User(s)&quot; means any registered user of the Platform.</p>

<p><strong>2.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>License Grant.</strong>&nbsp;&nbsp; In exchange for the entry of certain and complete data about Licensee, the sufficiency of which is determined by Licensor, Licensor hereby grants you a revocable, non-exclusive, non-transferable, non-sublicensable, limited license to access and use the Platform and to participate in the Marketplace and for other purposes related to the engineering, procurement, bidding and construction of solar energy generation projects subject to the limitations herein for the Trial Period. Upon completion of the Trial Period the License Grant will continue into the Initial Term upon payment of fees described in Section 5.&nbsp;&nbsp;All rights not expressly granted to you are reserved by Wiser Capital and its licensors.</p>

<p>&nbsp;</p>

<p><strong>3.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Access to the Platform.</strong>&nbsp;&nbsp;The Platform is hosted by Wiser Capital or its contractors at&nbsp;<a href="http://www.wisercapital.com/">www.wisercapital.com</a>&nbsp;&nbsp;and Licensee must register and obtain a username and password to access the functionalities of the Platform.&nbsp;&nbsp;Licensee may be required to complete all information on the registration form, and then be approved by Licensor, in order to access and use the Platform and Marketplace.&nbsp;&nbsp;Each Licensee must (1) complete a Solar Integrator Profile and (2) submit such completed Profile to Wiser Capital through the Platform as application for use of the Platform.&nbsp;&nbsp;Wiser Capital shall review such application and grant or deny approval to participate in the Platform and Marketplace in its sole discretion.&nbsp;Approval to use the Platform and granting of a Seat License does not indicate or guarantee success in development of or financing for Projects.&nbsp;Licensee represents and warrants that it will truthfully complete all required information in the registration form.</p>

<p>&nbsp;</p>

<p><strong>4.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Unauthorized Use.&nbsp;&nbsp;</strong>Your use of the Platform is also subject to the Terms and Conditions contained in the Website Privacy Policy:&nbsp;<a href="http://www.wisercapital.com/about/privacy">http://www.wisercapital.com/about/privacy</a><strong>.&nbsp;&nbsp;</strong>In addition, any activity related to a solar energy generation project that uses the Platform or the Marketplace is subject to the following conditions.</p>

<p><strong>a.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You may not use the Platform if you are a Direct Competitor of Wiser Capital, except with prior written approval by an authorized officer of Wiser Capital who has been informed that you are a Direct Competitor.&nbsp;&nbsp;You may not access the Platform for purposes of monitoring its availability, performance or functionality, or for any other benchmarking or competitive purposes.</p>

<p><strong>b.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You may not: (i) sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Platform, the Marketplace or any Content provided to you through your use of the Services without Wiser Capital&rsquo;s express written consent except as otherwise provided herein; (ii) modify or make derivative works based upon the Platform or the Content; (iii) create Internet &quot;links&quot; to the Service except for access to the Home Page, or &quot;frame&quot; or &quot;mirror&quot; any Content on any other server or wireless or Internet-based device; or (iv) reverse engineer or access the Platform in order to (a) build a competitive product or service, (b) build a product using similar ideas, features, functions or graphics of the Service, or (c) copy any ideas, features, functions or graphics of the Service.</p>

<p><strong>c.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You may not share User licenses as each User must register with the Platform.</p>

<p><strong>d.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You represent and warrant that you will not enter into any agreement with a Lead obtained through your use of the Platform or the Marketplace for engineering, procurement, or construction of a solar energy generation project outside of the Platform or the Marketplace without the express written consent of Wiser Capital.&nbsp;&nbsp;The intent of this provision is to prevent circumvention of the Platform and maintain quality of service for all Stakeholders involved in Lead development.&nbsp; If you wish to remove a lead from the Platform please contact Wiser Capital for a process to accommodate this.&nbsp;If, however, you do not contact Wiser Capital about such an issue, and it can be shown by a preponderance of the evidence that you have violated this provision, you agree to pay Wiser Capital a finder&rsquo;s fee of&nbsp;<strong>10% (ten percent)&nbsp;</strong>of the total compensation you are paid for construction of a PV System for such Lead.&nbsp;&nbsp;Moreover, Licensee agrees violation of this representation and warranty will provide Licensor damages that would be difficult to quantify and, therefore, Licensor may enjoin Licensee from entering into such an outside agreement with a Lead obtained through use of the Platform and participation in the Marketplace.&nbsp;</p>

<p><strong>e.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You shall not make any material misrepresentations to Wiser Capital or any other User of the Platform.&nbsp;</p>

<p>&nbsp;</p>

<p><strong>5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fees</strong>.</p>

<p>a.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seat License Fee.&nbsp;&nbsp;&nbsp;Wiser Capital offers access to the Platform under an annual, or longer, Seat License contract. The fees for such contracts are paid monthly, in advance, following any Trial Period agreed to at the time of License Grant (the Initial Term) according to the terms in 4c and 4d.&nbsp;Licensee agrees to pay the then-current Seat License fees for each Seat License it desires to purchase.&nbsp;&nbsp;Licensee can request a pricing chart with current fee structures by emailing mjb@wisercapital.com.&nbsp;&nbsp;Wiser Capital may modify the per-Seat License fees and contract periods in its sole discretion, such changes to be effective at the end of the current contract periods for ending Licenses, and thereafter, and subject to the Renewal terms in Section 5. Fees for other services will be charged on an as-quoted basis. Wiser Capital fees are exclusive of all taxes, levies, or duties imposed by taxing authorities, and you will be responsible for payment of all such taxes, levies, or duties, excluding only United States (federal or state) taxes based solely on Wiser Capital&#39;s income.&nbsp;</p>

<p>b.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Purchase of Licenses.&nbsp;&nbsp;An authorized License Administrator, as designated by Licensee, may acquire initial or additional seat licenses, upon registering for its Platform account.&nbsp;&nbsp;Additional&nbsp;Licenses will be subject to the following: (i) added licenses will be coterminous with the first-existing then current License Term acquired by Licensee (either Initial Term or Renewal Term); (ii) the license fee for the added licenses will be the then-current, generally applicable license fee, unless, at Licensor&rsquo;s sole discretion, it agrees to honor a previously agreed to License Fee structure, such structure to be approved in writing by Licensor; and (iii) licenses added in the middle of a billing month may be charged a prorated fee for that month&rsquo;s use that will be added to the fees assessed at the next billing cycle.&nbsp;&nbsp;</p>

<p>c.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Billing.&nbsp;Wiser Capital charges and collects Seat License fees in advance, at the start of each month, for access to the Platform and its Services, for the duration of the contract period for Seat Licenses. Wiser Capital will automatically bill your credit card each month or as otherwise mutually agreed upon. You represent and warrant that you will to provide Wiser Capital with complete and accurate billing and contact information. This information includes the legal name of your Company, street address, e-mail address, and name and telephone number of an authorized billing contact and License Administrator, and unless mutually agreed otherwise, your credit card information.&nbsp;&nbsp;You agree to provide Licensor notice of any changes to your billing or credit card information within 30 days of such change being effective.&nbsp;&nbsp;If you believe your bill is incorrect, you must contact us in writing within 60 days of the invoice date of the invoice containing the amount in question to be eligible to receive an adjustment or credit.</p>

<p>d.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Payment.&nbsp;&nbsp;You will pay all fees or charges to your account in accordance with the fees, charges, and billing terms in effect at the time a fee or charge is due and payable.&nbsp;&nbsp;Payments must be made in advance unless otherwise mutually agreed upon.&nbsp;&nbsp;All payment obligations are non-cancelable and all amounts paid are nonrefundable. You are responsible for paying for all active Seat Licenses subscribed for, whether or not such Seat Licenses are actively used.&nbsp;&nbsp;All pricing terms are confidential, and you agree not to disclose them to any third party.&nbsp;&nbsp;If you are subscribing to the Service through a sponsor that subsidizes the cost of the Service, it is anticipated that the sponsor will make payments to Licensor on your behalf, but you will remain responsible for all fees or charges that you incur.</p>

<p>e.&nbsp;&nbsp;&nbsp; Trial Period.&nbsp;&nbsp;There is no fee for creating an initial account and registering to use the Platform during the initial Trial Period, the length and/or extension of which, as well as the number of Seat Licenses to be granted access, are determined solely at the discretion of Licensor.&nbsp;&nbsp;Once Initial Term has started additional Trial Periods will not be granted to Seat Licenses that are added by the Licensee Administrator. Your adherence to the obligations set forth herein and your full completion of required information for access and approval to use the Platform and participate in the Marketplace shall be considered sufficient consideration for the functionalities obtained through this License Agreement during the Trial Period.</p>

<p>f.&nbsp;&nbsp;&nbsp;Additional Fees.&nbsp;&nbsp;Licensor may charge you additional fees in certain circumstances, including:</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A User may wish to engage Wiser Capital to perform fee-based project management and/or consulting services related to a solar energy generation project. Such services will be contracted on an as needed, T&amp;M basis or other mutually agreeable schedule to be detailed separately from this Agreement.</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A Solar Integrator may be charged an origination fee of a certain percentage of the total engineering, procurement and construction costs if such System Integrator is awarded a project from the Marketplace.&nbsp;&nbsp;Such terms will be expressly agreed to at the time a System Integrator submits a proposal to a Host Facility through the use of the Marketplace. Please contact Wiser Capital directly for more information about these fees.</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iii&nbsp;&nbsp;&nbsp;&nbsp;Each User is allowed a maximum amount of disk storage space at no charge for each User.&nbsp; If the amount of disk storage required exceeds these limits, you may be charged additional storage fees or denied additional storage. Wiser Capital wants you to use the Platform and has set storage limits that are significantly higher than what heavy and consistent use will foreseeably generate, and this term is intended to prevent abuse and misuse of the Platform&rsquo;s storage capacity. Wiser Capital will use reasonable efforts to notify you when storage used per license reaches approximately 90% of the maximum; however, any failure by Wiser Capital to so notify you will not affect this provision. Wiser Capital reserves the right to establish or modify its general practices and limits relating to storage of Customer Data.</p>

<p>&nbsp;</p>

<p><strong>6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Term.</strong>&nbsp;The Initial Term of the License Agreement shall begin upon the Effective Date and shall continue in force for the term indicated during the purchase of the Seat License.&nbsp;&nbsp;Upon the expiration of the Initial Term, the License Agreement will automatically renew for one (1) year Renewal Term(s) for the number of Seat Licenses currently owned at the then-current one-year Seat License fees. A fee schedule&nbsp;can be requested by emailing tde@wisercapital.com.&nbsp;&nbsp;&nbsp;</p>

<p>&nbsp;</p>

<p><strong>7.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Termination</strong>.&nbsp;</p>

<p>a.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Termination by Licensee.&nbsp;Licensee may choose to terminate it licenses before the end of any Trial Period at no charge, or at the end of the contract period by notifying Licensor in writing of its desire not to have its licenses renewed under Section 5.</p>

<p>b.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Termination by Licensor.&nbsp;&nbsp;Wiser Capital may terminate all, or an individual, Seat License at any time in its own discretion by providing Licensee with at least five (5) days&rsquo; written notice of such termination.&nbsp;&nbsp;Such termination shall not affect your obligation to pay any fees which you have incurred.</p>

<p>c.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Effect of Termination, No Cause.&nbsp;&nbsp;Upon termination, your right to access or use the Platform, the Content contained therein, or the Marketplace immediately ceases.&nbsp;&nbsp;In the event this License Agreement is terminated (other than by reason of your breach) or by your written request, Wiser Capital may make available to you, at your expense, a file of your Customer Data for up to thirty (30) days after the termination date.&nbsp;&nbsp;</p>

<p>d.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Termination for For Non-Payment, or For Cause.&nbsp;&nbsp;In addition to any other rights granted to the Platform herein, Wiser Capital reserves the right to suspend or terminate this License Agreement and your access to the Platform&rsquo;s Service and the Marketplace if your account becomes delinquent (falls into arrears).&nbsp;Delinquent invoices (accounts in arrears) are subject to interest of 1.0% per month on any outstanding balance, or the maximum permitted by law, whichever is less, plus all expenses of collection.&nbsp;&nbsp;You will continue to be charged for each Seat License during any period of suspension.&nbsp;&nbsp;If Wiser Capital terminates this Agreement, you will be obligated to pay the balance due on your account computed in accordance with the Fees section above for the remainder of the then-current term.&nbsp;&nbsp;You agree that Wiser Capital may charge such unpaid fees to your credit card or otherwise bill you for such unpaid fees.&nbsp;&nbsp;Wiser Capital may impose a reconnection fee in the event you are suspended and thereafter request access to the Service in its sole discretion. &nbsp;Upon termination for cause, Wiser Capital will have no obligation to maintain, forward, or return any Customer Data.&nbsp;&nbsp;Wiser Capital reserves the right to save, withhold, remove and/or discard Customer Data without notice for any breach, including, without limitation, your non-payment.</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>

<p><strong>8.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Your Responsibilities.</strong>&nbsp;&nbsp;You represent and warrant through your use of the Platform and the Marketplace that you have the authority of your Company to participate and make decisions on its behalf.&nbsp;&nbsp;Through the use of the Services, each User represents he/she has the authority to bind the Company to such actions undertaken by the User.&nbsp;&nbsp;Thus, you and your Company are responsible for all activity occurring under your account and you represent and warrant that you will abide by all applicable local, state, national and foreign laws, treaties and regulations in connection with your use of the Platform and the Marketplace including those related to data privacy, international communications and the transmission of technical or personal data. You will: (i) notify Wiser Capital immediately of any unauthorized use of any password or account or any other known or suspected breach of security; (ii) report to Wiser Capital immediately and use reasonable efforts to stop immediately any copying or distribution of Content that is known or suspected by you; and (iii) not impersonate another User or provide false identity information to gain access to or use the Platform or participate in the Marketplace.</p>

<p>&nbsp;</p>

<p><strong>9.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Account Information and Customer Data.</strong>&nbsp;You represent and warrant that all Customer Data you input, submit, upload, or otherwise provide during your use of the Services is truthful and accurate.&nbsp;&nbsp;You represent and warrant that you have all necessary right, title, or necessary license rights to use, post, or submit such Customer Data onto the Platform or through the Marketplace.&nbsp;&nbsp;You are responsible for the quality, integrity, legality, reliability, appropriateness, and confidentiality of all Customer Data you submit during your use of the Services.&nbsp;&nbsp;Wiser Capital disclaims all responsibility related to any errors or inaccuracies in any Customer Data that is used to provide the Services.&nbsp;&nbsp;You shall maintain a backup copy of all Customer Data.&nbsp;&nbsp;Wiser Capital shall not be responsible for any destruction, damage, and loss of any Customer Data while it is stored by Wiser Capital.</p>

<p>&nbsp;</p>

<p><strong>10.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Intellectual Property Ownership.</strong></p>

<p><strong>a.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wiser Capital and its licensors (where applicable) own all right, title and interest, including all related Intellectual Property Rights, in and to the Content, the Services, and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you relating to the Services. The Wiser Capital name, the Wiser Capital logo, and the product and services names associated with the Platform are trademarks of Wiser Capital LLC, or third parties and, except as specifically granted herein, no right or license is granted to you to use them in any manner without Wiser Capital&rsquo;s prior written consent.</p>

<p><strong>b.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You shall retain ownership in all Customer Data submitted or provided during your use of the Services.&nbsp;&nbsp;However, you hereby grant Wiser Capital a perpetual, limited, non-exclusive, worldwide, royalty-free, sub-licensable license to use your Customer Data for the purposes of performing the Services provided by the Platform.</p>

<p>&nbsp;</p>

<p><strong>11.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Third Party Interactions.&nbsp;</strong>During use of the Service, you may enter into correspondence or commercial transactions with other Users of the Platform or Marketplace.&nbsp;&nbsp;You and such third-party Users shall be solely responsible for any correspondence or commercial transactions between you and such third-party User.&nbsp;&nbsp;Wiser Capital will have no liability, obligation or responsibility to monitor such transactions or for any such correspondence between you and any other User except as expressly indicated herein.&nbsp;&nbsp;Wiser Capital has no affiliation, sponsorship, agency, or partnership with any third-party User of the Services unless such parties explicitly form such a relationship through contract or other legal entity.&nbsp;</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>12.</strong>&nbsp;&nbsp;<strong>Confidential Information.&nbsp;</strong>Except as otherwise required by law, each Party shall keep all Confidential Information in confidence and shall not, without the other Party&rsquo;s prior written consent, disclose or otherwise make available, directly or indirectly, any Confidential Information to anyone other than that Party&rsquo;s employees and of their representatives who need to know the same in the performance of each respective obligations hereunder.</p>

<p><strong>a.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Confidential Information: Definition.&nbsp;&nbsp;In addition, each Party acknowledges and agrees that it may have access to, or become acquainted with, Confidential Information of the other&nbsp;Party in the course of the performance of its obligations under this License Agreement.&nbsp;&nbsp;&ldquo;Confidential Information&rdquo; means all information concerning a Party, its affiliates or any of its respective businesses, assets, products, services, employees, or customers, or of any third party in the possession of a Party or any of its affiliates, that is designated by a Party or any of its affiliates as confidential or proprietary or that is customarily or legally required to be protected from public disclosure, regardless of whether such information is provided to the other Party orally, in writing or other tangible form, via email or in electronic form, or is obtained through visual observation.&nbsp;&nbsp;Confidential Information includes, without limitation, access information, account data, end-user personal information, technical, financial or business information or data; strategies and plans; research and development plans and results; pricing information; information regarding products and services or product or service models, prototypes or samples; product schematics, documentation and manuals; proprietary methods, techniques, designs and processes; inventions, works of authorship, trade secrets and discoveries; software source code and object code; data, algorithms and flow-charts used by or for, or otherwise relating to, such software; lists of or data regarding actual or potential customers or suppliers; and any information based on or derived from any Confidential Information.&nbsp;</p>

<p><strong>b.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exceptions. Confidential Information shall not include any information that: (a) was known to the other Party prior to execution of this License Agreement without an obligation to keep it confidential; (b) was lawfully obtained by the other Party from a third party without any obligation of confidentiality; (c) is, at the time of disclosure, in the public knowledge; (d) becomes part of the public knowledge after disclosure by publication or otherwise, except by breach of this License Agreement; (e) developed by or for the other Party independently and apart from this License Agreement and without use of the Confidential Information; or (f) is otherwise knowledge possessed by the other Party or its employees as the result of their industry experience or education.</p>

<p><strong>c.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Other Disclosure.&nbsp;&nbsp;If a Party is required to disclose or make available any Confidential Information of the other Party pursuant to a valid court order or other legal requirement, the Party shall promptly notify the other Party of such requirement in writing as soon as commercially reasonable and cooperate and assist the other Party in any efforts undertaken by the other Party to limit the disclosure.&nbsp;&nbsp;Notwithstanding the foregoing, in all cases of a required disclosure, Disclosing Party shall limit the information disclosed or made available to the minimum required by law.</p>

<p><strong>13.</strong>&nbsp;&nbsp;<strong>Disclaimer of Warranties.</strong></p>

<p><strong>a.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;WISER CAPITAL AND ITS LICENSORS PROVIDE THE SERVICES, THE PLATFORM, THE MARKETPLACE, AND ALL CONTENT TO YOU STRICTLY ON AN &quot;AS IS&quot; BASIS. WISER CAPITAL DISCLAIMS ALL CONDITIONS, REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.</p>

<p><strong>b.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;WISER CAPITAL MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, TRUTH, AVAILABILITY, ACCURACY OR COMPLETENESS OF THE SERVICES, THE PLATFORM, THE MARKETPLACE, OR ANY CONTENT OR OTHER USER&rsquo;S CUSTOMER DATA.&nbsp;&nbsp;WE DO NOT REPRESENT OR WARRANT THAT (A) THE USE OF THE SERVICES, PLATFORM, OR MARKETPLACE WILL BE TIMELY, UNINTERRUPTED, ERROR-FREE OR OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM OR DATA, (B) THE SERVICES, PLATFORM, OR MARKETPLACE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (C) ANY STORED CUSTOMER DATA WILL BE ACCURATE OR RELIABLE, (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (E) ERRORS OR DEFECTS WILL BE CORRECTED, OR (F) THE SERVICES OR THE SERVER(S) THAT MAKE THE SERVICES AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>

<p>&nbsp;</p>

<p><strong>14.</strong>&nbsp;&nbsp;<strong>&nbsp;Indemnification:&nbsp;</strong>You will indemnify and hold Wiser Capital, its licensors, other Users, and each such Party&#39;s parent organizations, subsidiaries, affiliates, officers, directors, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys&#39; fees and costs) arising out of or in connection with: (i) a claim alleging that your unauthorized use of the Platform or the Services infringes the rights of, or has caused harm to, a third party; (ii) a claim, which if true, would constitute a violation by you of your representations and warranties; or (iii) a claim arising from the breach by you of this License Agreement, provided in any such case that Wiser Capital (a) gives written notice of the claim promptly to you; (b) gives you sole control of the defense and settlement of the claim (provided that you may not settle or defend any claim unless you unconditionally release Wiser Capital of all liability and such settlement does not affect Wiser Capital&#39;s business or Service); (c) provides to you, at your expense, all reasonably available information and assistance; and (d) has not compromised or settled such claim.</p>

<p>&nbsp;</p>

<p><strong>15.</strong>&nbsp;&nbsp;<strong>Limitation of Liability:&nbsp;</strong>IN NO EVENT WILL WISER CAPITAL&rsquo;S OR ITS LICENSORS&rsquo; AGGREGATE LIABILITY EXCEED THE AMOUNTS ACTUALLY PAID BY AND/OR DUE FROM YOU OR YOUR COMPANY IN THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH CLAIM.&nbsp;&nbsp;IN NO EVENT WILL WISER CAPITAL AND/OR ITS LICENSORS BE LIABLE TO YOU OR YOUR COMPANY FOR ANY INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES OF ANY TYPE OR KIND (INCLUDING LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE) ARISING OUT OF, OR IN ANY WAY CONNECTED WITH THIS SERVICE, INCLUDING BUT NOT LIMITED TO THE USE OR INABILITY TO USE THE SERVICE, OR FOR ANY CONTENT OBTAINED FROM OR THROUGH THE SERVICE, ANY INTERRUPTION, INACCURACY, ERROR, OR OMISSION REGARDLESS OF CAUSE IN THE CONTENT, EVEN IF WISER CAPITAL ITS LICENSORS HAVE BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

<p>&nbsp;</p>

<p><strong>16.</strong>&nbsp;&nbsp;<strong>Notice:</strong>&nbsp;</p>

<p><strong>a.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wiser Capital may provide you notice by means of: a general notice on the Platform; electronic mail to the e-mail address on record in your Platform account; or by first class mail or pre-paid post to the address on record in your Platform account.&nbsp;&nbsp;Such notice will be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email).</p>

<p><strong>b.</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You may give notice to Wiser Capital Platform at any time by a letter delivered by nationally recognized overnight delivery service or certified first class postage prepaid mail to Wiser Capital at the following addresses: Wiser Capital Platform, Inc., Attn: Legal Department, 2020 Alameda Padre Serra, Suite 220, Santa Barbara, CA, 93103.&nbsp;&nbsp;Such notice will be deemed given when received by Wiser Capital Platform.</p>

<p>&nbsp;</p>

<p><strong>17.</strong>&nbsp;&nbsp;<strong>Modification to Terms:&nbsp;</strong>Wiser Capital reserves the right to modify this License Agreement or its policies relating to the Service at any time.&nbsp;&nbsp;Wiser Capital will provide notice to you in the event the terms of this License Agreement are modified.&nbsp;&nbsp;Continued use of the Service after receipt of the notice of any such changes will constitute your consent to any modifications to this License Agreement.</p>

<p>&nbsp;</p>

<p><strong>18.</strong>&nbsp;&nbsp;<strong>Assignment; Change in Control:</strong>&nbsp;&nbsp;This License Agreement may not be assigned by you without the prior written consent of Wiser Capital.&nbsp;This License Agreement may be assigned by Wiser Capital without your consent to (i) a parent or subsidiary, (ii) an acquirer of assets, or (iii) a successor by merger. Any purported assignment in violation of this section will be void.&nbsp;&nbsp;Any actual or proposed change in control that results in a Direct Competitor of Wiser Capital directly or indirectly owning or controlling any portion of you or your Company will terminate this License Agreement for cause immediately.</p>

<p>&nbsp;</p>

<p><strong>19.</strong>&nbsp;&nbsp;<strong>Choice of Law:</strong>&nbsp;&nbsp;This License Agreement will be governed by California law and controlling United States federal law, without regard to the choice or conflicts of law provisions of any jurisdiction, and any disputes, actions, claims or causes of action arising out of or in connection with this License Agreement or the Service will be subject to the exclusive jurisdiction of the state and federal courts located in Santa Barbara, California.</p>

<p>&nbsp;</p>

<p><strong>20.</strong>&nbsp;&nbsp;<strong>Severability</strong>:&nbsp;&nbsp;If any provision of this License Agreement is held by a court of competent jurisdiction to be invalid or unenforceable, then such provision(s) will be construed, as nearly as possible, to reflect the intentions of the invalid or unenforceable provision(s), with all other provisions remaining in full force and effect. No joint venture, partnership, employment, or agency relationship exists between you and Wiser Capital as a result of this License Agreement or use of the Service.</p>

<p>&nbsp;</p>

<p><strong>21.</strong>&nbsp;&nbsp;<strong>Waiver:</strong>&nbsp;The failure of Wiser Capital to enforce any right or provision in this License Agreement will not constitute a waiver of such right or provision unless acknowledged and agreed to by Wiser Capital in writing.</p>

<p>&nbsp;</p>

<p><strong>22.</strong>&nbsp;&nbsp;<strong>Entire Agreement:</strong>&nbsp;&nbsp;This License Agreement comprises the entire agreement between you and Wiser Capital and supersedes all prior or contemporaneous negotiations, discussions or agreements, whether written or oral, between the parties regarding the subject matter contained herein.&nbsp;&nbsp;No standard provisions, text, terms or conditions set forth on any other purchase order, preprinted form or document will add to or vary the terms and conditions of this License Agreement.</p>

<p>&nbsp;</p>

<p><strong>23.</strong>&nbsp;&nbsp;<strong>Survival:</strong>&nbsp;&nbsp;The following provisions of this License Agreement will survive the termination of this License Agreement for any reason. Sections 8 (Your Responsibilities), 9 (Account Information and Data), 10 (Intellectual Property Ownership), 11 (Third Party Interactions), 12 (Confidential Information), 13 (Disclaimer of Warranties), 14 (Indemnification), and 15 (Limitation of Liability).</p>

<p>&nbsp;</p>

