<?php

use Illuminate\Database\Seeder;

class RoutesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('routes')->delete();
        
        \DB::table('routes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'faust',
                'method' => 'GET',
                'path' => 'faust',
                'action_name' => 'App\\Http\\Controllers\\FaustController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'home',
                'method' => 'GET',
                'path' => 'home',
                'action_name' => 'App\\Http\\Controllers\\HomeController@index',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'welcome',
                'method' => 'GET',
                'path' => 'welcome',
                'action_name' => 'App\\Http\\Controllers\\HomeController@welcome',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'about.privacy',
                'method' => 'GET',
                'path' => 'about/privacy',
                'action_name' => 'App\\Http\\Controllers\\AboutController@privacy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'dashboard',
                'method' => 'GET',
                'path' => 'dashboard',
                'action_name' => 'App\\Http\\Controllers\\DashboardController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'admin.users.enable-selected',
                'method' => 'POST',
                'path' => 'admin/users/enableSelected',
                'action_name' => 'App\\Http\\Controllers\\UsersController@enableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'admin.users.disable-selected',
                'method' => 'POST',
                'path' => 'admin/users/disableSelected',
                'action_name' => 'App\\Http\\Controllers\\UsersController@disableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'admin.users.search',
                'method' => 'GET',
                'path' => 'admin/users/search',
                'action_name' => 'App\\Http\\Controllers\\UsersController@searchByName',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'admin.users.list',
                'method' => 'GET',
                'path' => 'admin/users/list',
                'action_name' => 'App\\Http\\Controllers\\UsersController@listByPage',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'admin.users.get-info',
                'method' => 'POST',
                'path' => 'admin/users/getInfo',
                'action_name' => 'App\\Http\\Controllers\\UsersController@getInfo',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:20',
                'updated_at' => '2016-07-20 20:45:20',
                'enabled' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'admin.users.store',
                'method' => 'POST',
                'path' => 'admin/users',
                'action_name' => 'App\\Http\\Controllers\\UsersController@store',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'admin.users.index',
                'method' => 'GET',
                'path' => 'admin/users',
                'action_name' => 'App\\Http\\Controllers\\UsersController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'admin.users.create',
                'method' => 'GET',
                'path' => 'admin/users/create',
                'action_name' => 'App\\Http\\Controllers\\UsersController@create',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'admin.users.show',
                'method' => 'GET',
                'path' => 'admin/users/{userId}',
                'action_name' => 'App\\Http\\Controllers\\UsersController@show',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'admin.users.patch',
                'method' => 'PATCH',
                'path' => 'admin/users/{userId}',
                'action_name' => 'App\\Http\\Controllers\\UsersController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'admin.users.update',
                'method' => 'PUT',
                'path' => 'admin/users/{userId}',
                'action_name' => 'App\\Http\\Controllers\\UsersController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'admin.users.destroy',
                'method' => 'DELETE',
                'path' => 'admin/users/{userId}',
                'action_name' => 'App\\Http\\Controllers\\UsersController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'admin.users.edit',
                'method' => 'GET',
                'path' => 'admin/users/{userId}/edit',
                'action_name' => 'App\\Http\\Controllers\\UsersController@edit',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'admin.users.confirm-delete',
                'method' => 'GET',
                'path' => 'admin/users/{userId}/confirm-delete',
                'action_name' => 'App\\Http\\Controllers\\UsersController@getModalDelete',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'admin.users.delete',
                'method' => 'GET',
                'path' => 'admin/users/{userId}/delete',
                'action_name' => 'App\\Http\\Controllers\\UsersController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'admin.users.enable',
                'method' => 'GET',
                'path' => 'admin/users/{userId}/enable',
                'action_name' => 'App\\Http\\Controllers\\UsersController@enable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'admin.users.disable',
                'method' => 'GET',
                'path' => 'admin/users/{userId}/disable',
                'action_name' => 'App\\Http\\Controllers\\UsersController@disable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'admin.users.replay-edit',
                'method' => 'GET',
                'path' => 'admin/users/{userId}/replayEdit',
                'action_name' => 'App\\Http\\Controllers\\UsersController@replayEdit',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'admin.roles.enable-selected',
                'method' => 'POST',
                'path' => 'admin/roles/enableSelected',
                'action_name' => 'App\\Http\\Controllers\\RolesController@enableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'admin.roles.disable-selected',
                'method' => 'POST',
                'path' => 'admin/roles/disableSelected',
                'action_name' => 'App\\Http\\Controllers\\RolesController@disableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'admin.roles.search',
                'method' => 'GET',
                'path' => 'admin/roles/search',
                'action_name' => 'App\\Http\\Controllers\\RolesController@searchByName',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'admin.roles.get-info',
                'method' => 'POST',
                'path' => 'admin/roles/getInfo',
                'action_name' => 'App\\Http\\Controllers\\RolesController@getInfo',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'admin.roles.store',
                'method' => 'POST',
                'path' => 'admin/roles',
                'action_name' => 'App\\Http\\Controllers\\RolesController@store',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'admin.roles.index',
                'method' => 'GET',
                'path' => 'admin/roles',
                'action_name' => 'App\\Http\\Controllers\\RolesController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'admin.roles.create',
                'method' => 'GET',
                'path' => 'admin/roles/create',
                'action_name' => 'App\\Http\\Controllers\\RolesController@create',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'admin.roles.show',
                'method' => 'GET',
                'path' => 'admin/roles/{roleId}',
                'action_name' => 'App\\Http\\Controllers\\RolesController@show',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'admin.roles.patch',
                'method' => 'PATCH',
                'path' => 'admin/roles/{roleId}',
                'action_name' => 'App\\Http\\Controllers\\RolesController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'admin.roles.update',
                'method' => 'PUT',
                'path' => 'admin/roles/{roleId}',
                'action_name' => 'App\\Http\\Controllers\\RolesController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'admin.roles.destroy',
                'method' => 'DELETE',
                'path' => 'admin/roles/{roleId}',
                'action_name' => 'App\\Http\\Controllers\\RolesController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'admin.roles.edit',
                'method' => 'GET',
                'path' => 'admin/roles/{roleId}/edit',
                'action_name' => 'App\\Http\\Controllers\\RolesController@edit',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'admin.roles.confirm-delete',
                'method' => 'GET',
                'path' => 'admin/roles/{roleId}/confirm-delete',
                'action_name' => 'App\\Http\\Controllers\\RolesController@getModalDelete',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:21',
                'updated_at' => '2016-07-20 20:45:21',
                'enabled' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'admin.roles.delete',
                'method' => 'GET',
                'path' => 'admin/roles/{roleId}/delete',
                'action_name' => 'App\\Http\\Controllers\\RolesController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'admin.roles.enable',
                'method' => 'GET',
                'path' => 'admin/roles/{roleId}/enable',
                'action_name' => 'App\\Http\\Controllers\\RolesController@enable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'admin.roles.disable',
                'method' => 'GET',
                'path' => 'admin/roles/{roleId}/disable',
                'action_name' => 'App\\Http\\Controllers\\RolesController@disable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'admin.menus.save',
                'method' => 'POST',
                'path' => 'admin/menus',
                'action_name' => 'App\\Http\\Controllers\\MenusController@save',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'admin.menus.index',
                'method' => 'GET',
                'path' => 'admin/menus',
                'action_name' => 'App\\Http\\Controllers\\MenusController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'admin.menus.get-data',
                'method' => 'GET',
                'path' => 'admin/menus/getData/{menuId}',
                'action_name' => 'App\\Http\\Controllers\\MenusController@getData',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'admin.menus.confirm-delete',
                'method' => 'GET',
                'path' => 'admin/menus/{menuId}/confirm-delete',
                'action_name' => 'App\\Http\\Controllers\\MenusController@getModalDelete',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'admin.menus.delete',
                'method' => 'GET',
                'path' => 'admin/menus/{menuId}/delete',
                'action_name' => 'App\\Http\\Controllers\\MenusController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'admin.modules.index',
                'method' => 'GET',
                'path' => 'admin/modules',
                'action_name' => 'App\\Http\\Controllers\\ModulesController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'admin.modules.initialize',
                'method' => 'GET',
                'path' => 'admin/modules/{slug}/initialize',
                'action_name' => 'App\\Http\\Controllers\\ModulesController@initialize',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'admin.modules.uninitialize',
                'method' => 'GET',
                'path' => 'admin/modules/{slug}/uninitialize',
                'action_name' => 'App\\Http\\Controllers\\ModulesController@uninitialize',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'admin.modules.enable',
                'method' => 'GET',
                'path' => 'admin/modules/{slug}/enable',
                'action_name' => 'App\\Http\\Controllers\\ModulesController@enable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'admin.modules.disable',
                'method' => 'GET',
                'path' => 'admin/modules/{slug}/disable',
                'action_name' => 'App\\Http\\Controllers\\ModulesController@disable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'admin.modules.enable-selected',
                'method' => 'POST',
                'path' => 'admin/modules/enableSelected',
                'action_name' => 'App\\Http\\Controllers\\ModulesController@enableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'admin.modules.disable-selected',
                'method' => 'POST',
                'path' => 'admin/modules/disableSelected',
                'action_name' => 'App\\Http\\Controllers\\ModulesController@disableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'admin.modules.optimize',
                'method' => 'GET',
                'path' => 'admin/modules/optimize',
                'action_name' => 'App\\Http\\Controllers\\ModulesController@optimize',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'admin.permissions.generate',
                'method' => 'GET',
                'path' => 'admin/permissions/generate',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@generate',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'admin.permissions.enable-selected',
                'method' => 'POST',
                'path' => 'admin/permissions/enableSelected',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@enableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'admin.permissions.disable-selected',
                'method' => 'POST',
                'path' => 'admin/permissions/disableSelected',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@disableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'admin.permissions.store',
                'method' => 'POST',
                'path' => 'admin/permissions',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@store',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'admin.permissions.index',
                'method' => 'GET',
                'path' => 'admin/permissions',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'admin.permissions.create',
                'method' => 'GET',
                'path' => 'admin/permissions/create',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@create',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'admin.permissions.show',
                'method' => 'GET',
                'path' => 'admin/permissions/{permissionId}',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@show',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'admin.permissions.patch',
                'method' => 'PATCH',
                'path' => 'admin/permissions/{permissionId}',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'admin.permissions.update',
                'method' => 'PUT',
                'path' => 'admin/permissions/{permissionId}',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'admin.permissions.destroy',
                'method' => 'DELETE',
                'path' => 'admin/permissions/{permissionId}',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:22',
                'updated_at' => '2016-07-20 20:45:22',
                'enabled' => 1,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'admin.permissions.edit',
                'method' => 'GET',
                'path' => 'admin/permissions/{permissionId}/edit',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@edit',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'admin.permissions.confirm-delete',
                'method' => 'GET',
                'path' => 'admin/permissions/{permissionId}/confirm-delete',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@getModalDelete',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'admin.permissions.delete',
                'method' => 'GET',
                'path' => 'admin/permissions/{permissionId}/delete',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'admin.permissions.enable',
                'method' => 'GET',
                'path' => 'admin/permissions/{permissionId}/enable',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@enable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'admin.permissions.disable',
                'method' => 'GET',
                'path' => 'admin/permissions/{permissionId}/disable',
                'action_name' => 'App\\Http\\Controllers\\PermissionsController@disable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'admin.routes.load',
                'method' => 'GET',
                'path' => 'admin/routes/load',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@load',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'admin.routes.enable-selected',
                'method' => 'POST',
                'path' => 'admin/routes/enableSelected',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@enableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'admin.routes.disable-selected',
                'method' => 'POST',
                'path' => 'admin/routes/disableSelected',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@disableSelected',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'admin.routes.save-perms',
                'method' => 'POST',
                'path' => 'admin/routes/savePerms',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@savePerms',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'admin.routes.search',
                'method' => 'GET',
                'path' => 'admin/routes/search',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@searchByName',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'admin.routes.get-info',
                'method' => 'POST',
                'path' => 'admin/routes/getInfo',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@getInfo',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'admin.routes.store',
                'method' => 'POST',
                'path' => 'admin/routes',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@store',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'admin.routes.index',
                'method' => 'GET',
                'path' => 'admin/routes',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'admin.routes.create',
                'method' => 'GET',
                'path' => 'admin/routes/create',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@create',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'admin.routes.show',
                'method' => 'GET',
                'path' => 'admin/routes/{routeId}',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@show',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'admin.routes.patch',
                'method' => 'PATCH',
                'path' => 'admin/routes/{routeId}',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'admin.routes.update',
                'method' => 'PUT',
                'path' => 'admin/routes/{routeId}',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'admin.routes.destroy',
                'method' => 'DELETE',
                'path' => 'admin/routes/{routeId}',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'admin.routes.edit',
                'method' => 'GET',
                'path' => 'admin/routes/{routeId}/edit',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@edit',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'admin.routes.confirm-delete',
                'method' => 'GET',
                'path' => 'admin/routes/{routeId}/confirm-delete',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@getModalDelete',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'admin.routes.delete',
                'method' => 'GET',
                'path' => 'admin/routes/{routeId}/delete',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'admin.routes.enable',
                'method' => 'GET',
                'path' => 'admin/routes/{routeId}/enable',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@enable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'admin.routes.disable',
                'method' => 'GET',
                'path' => 'admin/routes/{routeId}/disable',
                'action_name' => 'App\\Http\\Controllers\\RoutesController@disable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'admin.audit.index',
                'method' => 'GET',
                'path' => 'admin/audit',
                'action_name' => 'App\\Http\\Controllers\\AuditsController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'admin.audit.purge',
                'method' => 'GET',
                'path' => 'admin/audit/purge',
                'action_name' => 'App\\Http\\Controllers\\AuditsController@purge',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'admin.audit.replay',
                'method' => 'GET',
                'path' => 'admin/audit/{auditId}/replay',
                'action_name' => 'App\\Http\\Controllers\\AuditsController@replay',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'admin.audit.show',
                'method' => 'GET',
                'path' => 'admin/audit/{auditId}/show',
                'action_name' => 'App\\Http\\Controllers\\AuditsController@show',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:23',
                'updated_at' => '2016-07-20 20:45:23',
                'enabled' => 1,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'admin.settings.index',
                'method' => 'GET',
                'path' => 'admin/settings',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_flash_warning',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'companies.list',
                'method' => 'GET',
                'path' => 'admin/companies',
                'action_name' => 'App\\Http\\Controllers\\CompanyController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'companies.datatable',
                'method' => 'GET',
                'path' => 'admin/companies/datatable',
                'action_name' => 'App\\Http\\Controllers\\CompanyController@dataTable',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'companies.create',
                'method' => 'GET',
                'path' => 'admin/companies/create',
                'action_name' => 'App\\Http\\Controllers\\CompanyController@create',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'companies.store',
                'method' => 'POST',
                'path' => 'admin/companies',
                'action_name' => 'App\\Http\\Controllers\\CompanyController@store',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'companies.edit',
                'method' => 'GET',
                'path' => 'admin/companies/edit/{id}',
                'action_name' => 'App\\Http\\Controllers\\CompanyController@edit',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'companies.update',
                'method' => 'PATCH',
                'path' => 'admin/companies/{id}',
                'action_name' => 'App\\Http\\Controllers\\CompanyController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'companies.confirm-delete',
                'method' => 'GET',
                'path' => 'admin/companies/{id}/confirm-delete',
                'action_name' => 'App\\Http\\Controllers\\CompanyController@getModalDelete',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'companies.delete',
                'method' => 'GET',
                'path' => 'admin/companies/{id}/delete',
                'action_name' => 'App\\Http\\Controllers\\CompanyController@destroy',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'test-acl.home',
                'method' => 'GET',
                'path' => 'test-acl/home',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_acl_home',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'test-acl.do-not-pre-load',
                'method' => 'GET',
                'path' => 'test-acl/do-not-pre-load',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_acl_do_not_load',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:49:58',
                'enabled' => 1,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'test-acl.no-perm',
                'method' => 'GET',
                'path' => 'test-acl/no-perm',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_acl_no_perm',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'test-acl.basic-authenticated',
                'method' => 'GET',
                'path' => 'test-acl/basic-authenticated',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_acl_basic_authenticated',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:49:58',
                'enabled' => 1,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'test-acl.guest-only',
                'method' => 'GET',
                'path' => 'test-acl/guest-only',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_acl_guest_only',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:49:58',
                'enabled' => 1,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'test-acl.open-to-all',
                'method' => 'GET',
                'path' => 'test-acl/open-to-all',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_acl_open_to_all',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'test-acl.admins',
                'method' => 'GET',
                'path' => 'test-acl/admins',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_acl_admins',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:49:58',
                'enabled' => 1,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'test-acl.power-users',
                'method' => 'GET',
                'path' => 'test-acl/power-users',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_acl_power_users',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'test-flash.home',
                'method' => 'GET',
                'path' => 'test-flash/home',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_flash_home',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'test-flash.success',
                'method' => 'GET',
                'path' => 'test-flash/success',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_flash_success',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'test-flash.info',
                'method' => 'GET',
                'path' => 'test-flash/info',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_flash_info',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'test-flash.warning',
                'method' => 'GET',
                'path' => 'test-flash/warning',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_flash_warning',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'test-flash.error',
                'method' => 'GET',
                'path' => 'test-flash/error',
                'action_name' => 'App\\Http\\Controllers\\TestController@test_flash_error',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'test-menus.home',
                'method' => 'GET',
                'path' => 'test-menus/home',
                'action_name' => 'App\\Http\\Controllers\\TestMenusController@test_menu_home',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'test-menus.one',
                'method' => 'GET',
                'path' => 'test-menus/one',
                'action_name' => 'App\\Http\\Controllers\\TestMenusController@test_menu_one',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'test-menus.two',
                'method' => 'GET',
                'path' => 'test-menus/two',
                'action_name' => 'App\\Http\\Controllers\\TestMenusController@test_menu_two',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'test-menus.two-a',
                'method' => 'GET',
                'path' => 'test-menus/two-a',
                'action_name' => 'App\\Http\\Controllers\\TestMenusController@test_menu_two_a',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'test-menus.two-b',
                'method' => 'GET',
                'path' => 'test-menus/two-b',
                'action_name' => 'App\\Http\\Controllers\\TestMenusController@test_menu_two_b',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:24',
                'updated_at' => '2016-07-20 20:45:24',
                'enabled' => 1,
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'test-menus.three',
                'method' => 'GET',
                'path' => 'test-menus/three',
                'action_name' => 'App\\Http\\Controllers\\TestMenusController@test_menu_three',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:45:25',
                'enabled' => 1,
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'rapyd.remote',
                'method' => 'GET',
                'path' => 'rapyd-ajax/{hash}',
                'action_name' => '\\Zofe\\Rapyd\\Controllers\\AjaxController@getRemote',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'hf.confirm-delete',
                'method' => 'GET',
                'path' => 'hf/{id}/confirm-delete',
                'action_name' => 'App\\Http\\Controllers\\HFController@getModalDelete',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'hf.delete',
                'method' => 'GET',
                'path' => 'hf/{id}/delete',
                'action_name' => 'App\\Http\\Controllers\\HFController@destroy',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'hf.dataroom',
                'method' => 'GET',
                'path' => 'hf/{id}/dataroom',
                'action_name' => 'App\\Http\\Controllers\\DocumentController@dataRoom',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'hf.download-document',
                'method' => 'GET',
                'path' => 'hf/{id}/dataroom/download/{key}/{type?}',
                'action_name' => 'App\\Http\\Controllers\\DocumentController@download',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'hf.facility-file-download',
                'method' => 'GET',
                'path' => 'hf/facility-file-download',
                'action_name' => 'App\\Http\\Controllers\\DocumentController@facilityFileDownload',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'hf.dataroom-files',
                'method' => 'GET',
                'path' => 'hf/{id}/dataroom-files',
                'action_name' => 'App\\Http\\Controllers\\DocumentController@dataRoomFiles',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'hf.upload-files',
                'method' => 'POST',
                'path' => 'api/hf/{id}/upload-files',
                'action_name' => 'App\\Http\\Controllers\\DocumentController@uploadFiles',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'hf.datatable',
                'method' => 'GET',
                'path' => 'hf/{solar_installer_id}/datatable',
                'action_name' => 'App\\Http\\Controllers\\HFController@dataTable',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'hf.wsar-score',
                'method' => 'GET',
                'path' => 'hf/{id}/wsar-score',
                'action_name' => 'App\\Http\\Controllers\\HFController@WSARScore',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'hf.facility-profile',
                'method' => 'GET',
                'path' => 'hf/{id}/facility-profile',
                'action_name' => 'App\\Http\\Controllers\\HFController@facilityProfile',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'hf.results',
                'method' => 'GET',
                'path' => 'hf/{id}/results',
                'action_name' => 'App\\Http\\Controllers\\ResultController@results',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'hf.index',
                'method' => 'GET',
                'path' => 'hf',
                'action_name' => 'App\\Http\\Controllers\\HFController@index',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'hf.create',
                'method' => 'GET',
                'path' => 'hf/create',
                'action_name' => 'App\\Http\\Controllers\\HFController@create',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'hf.store',
                'method' => 'POST',
                'path' => 'hf',
                'action_name' => 'App\\Http\\Controllers\\HFController@store',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'hf.show',
                'method' => 'GET',
                'path' => 'hf/{hf}',
                'action_name' => 'App\\Http\\Controllers\\HFController@show',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'hf.edit',
                'method' => 'GET',
                'path' => 'hf/{hf}/edit',
                'action_name' => 'App\\Http\\Controllers\\HFController@edit',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'hf.update',
                'method' => 'PUT',
                'path' => 'hf/{hf}',
                'action_name' => 'App\\Http\\Controllers\\HFController@update',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            135 => 
            array (
                'id' => 136,
                'name' => NULL,
                'method' => 'PATCH',
                'path' => 'hf/{hf}',
                'action_name' => 'App\\Http\\Controllers\\HFController@update',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            136 => 
            array (
                'id' => 137,
                'name' => 'hf.destroy',
                'method' => 'DELETE',
                'path' => 'hf/{hf}',
                'action_name' => 'App\\Http\\Controllers\\HFController@destroy',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
//            137 => 
//            array (
//                'id' => 138,
//                'name' => 'hf.preliminary-assessment',
//                'method' => 'GET',
//                'path' => 'hf/{id}/preliminary-assessment',
//                'action_name' => 'App\\Http\\Controllers\\HFController@preliminaryAssessment',
//                'permission_id' => 175,
//                'created_at' => '2016-07-20 20:45:25',
//                'updated_at' => '2016-07-20 20:48:57',
//                'enabled' => 1,
//            ),
            138 => 
            array (
                'id' => 139,
                'name' => 'si.datatable',
                'method' => 'GET',
                'path' => 'si/dataTable',
                'action_name' => 'App\\Http\\Controllers\\SIController@dataTable',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:49:58',
                'enabled' => 1,
            ),
            139 => 
            array (
                'id' => 140,
                'name' => 'si.index',
                'method' => 'GET',
                'path' => 'si',
                'action_name' => 'App\\Http\\Controllers\\SIController@index',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            140 => 
            array (
                'id' => 141,
                'name' => 'si.create',
                'method' => 'GET',
                'path' => 'si/create',
                'action_name' => 'App\\Http\\Controllers\\SIController@create',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:58',
                'enabled' => 1,
            ),
            141 => 
            array (
                'id' => 142,
                'name' => 'si.store',
                'method' => 'POST',
                'path' => 'si',
                'action_name' => 'App\\Http\\Controllers\\SIController@store',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            142 => 
            array (
                'id' => 143,
                'name' => 'si.show',
                'method' => 'GET',
                'path' => 'si/{si}',
                'action_name' => 'App\\Http\\Controllers\\SIController@show',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            143 => 
            array (
                'id' => 144,
                'name' => 'si.edit',
                'method' => 'GET',
                'path' => 'si/{si}/edit',
                'action_name' => 'App\\Http\\Controllers\\SIController@edit',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:58',
                'enabled' => 1,
            ),
            144 => 
            array (
                'id' => 145,
                'name' => 'si.update',
                'method' => 'PUT',
                'path' => 'si/{si}',
                'action_name' => 'App\\Http\\Controllers\\SIController@update',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:58',
                'enabled' => 1,
            ),
            145 => 
            array (
                'id' => 146,
                'name' => NULL,
                'method' => 'PATCH',
                'path' => 'si/{si}',
                'action_name' => 'App\\Http\\Controllers\\SIController@update',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            146 => 
            array (
                'id' => 147,
                'name' => 'si.destroy',
                'method' => 'DELETE',
                'path' => 'si/{si}',
                'action_name' => 'App\\Http\\Controllers\\SIController@destroy',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            147 => 
            array (
                'id' => 148,
                'name' => 'script',
                'method' => 'GET',
                'path' => 'script',
                'action_name' => 'App\\Http\\Controllers\\HomeController@script',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            148 => 
            array (
                'id' => 149,
                'name' => 'assets.list',
                'method' => 'GET',
                'path' => 'globals/assets',
                'action_name' => 'App\\Http\\Controllers\\AssetController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:45:26',
                'enabled' => 1,
            ),
            149 => 
            array (
                'id' => 150,
                'name' => 'assets.datatable',
                'method' => 'GET',
                'path' => 'globals/assets/datatable',
                'action_name' => 'App\\Http\\Controllers\\AssetController@dataTable',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            150 => 
            array (
                'id' => 151,
                'name' => 'assets.add',
                'method' => 'GET',
                'path' => 'globals/assets/{type}/add',
                'action_name' => 'App\\Http\\Controllers\\AssetController@create',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            151 => 
            array (
                'id' => 152,
                'name' => 'assets.edit',
                'method' => 'GET',
                'path' => 'globals/assets/{type}/edit/{id}',
                'action_name' => 'App\\Http\\Controllers\\AssetController@edit',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            152 => 
            array (
                'id' => 153,
                'name' => 'assets.store',
                'method' => 'POST',
                'path' => 'globals/assets',
                'action_name' => 'App\\Http\\Controllers\\AssetController@store',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:45:26',
                'enabled' => 1,
            ),
            153 => 
            array (
                'id' => 154,
                'name' => 'assets.update',
                'method' => 'PATCH',
                'path' => 'globals/assets/{id}',
                'action_name' => 'App\\Http\\Controllers\\AssetController@update',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:45:26',
                'enabled' => 1,
            ),
            154 => 
            array (
                'id' => 155,
                'name' => 'assets.confirm-delete',
                'method' => 'GET',
                'path' => 'globals/assets/{id}/confirm-delete',
                'action_name' => 'App\\Http\\Controllers\\AssetController@getModalDelete',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:45:26',
                'enabled' => 1,
            ),
            155 => 
            array (
                'id' => 156,
                'name' => 'assets.delete',
                'method' => 'GET',
                'path' => 'globals/assets/{id}/delete',
                'action_name' => 'App\\Http\\Controllers\\AssetController@destroy',
                'permission_id' => 1,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            156 => 
            array (
                'id' => 157,
                'name' => 'admin.agreements.index',
                'method' => 'GET',
                'path' => 'admin/agreements',
                'action_name' => 'App\\Http\\Controllers\\AgreementController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            157 => 
            array (
                'id' => 158,
                'name' => 'hf.map',
                'method' => 'GET',
                'path' => 'hf/{id}/map',
                'action_name' => 'App\\Http\\Controllers\\HFController@map',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            158 => 
            array (
                'id' => 159,
                'name' => 'hf.store-map',
                'method' => 'POST',
                'path' => 'hf/{id}/map/store',
                'action_name' => 'App\\Http\\Controllers\\HFController@storeMap',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            159 => 
            array (
                'id' => 160,
                'name' => 'hf.map-edit',
                'method' => 'GET',
                'path' => 'hf/{id}/map/edit',
                'action_name' => 'App\\Http\\Controllers\\HFController@editMap',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:48:56',
                'enabled' => 1,
            ),
            160 => 
            array (
                'id' => 161,
                'name' => 'hf.confirm-assessment',
                'method' => 'GET',
                'path' => 'hf/{id}/confirm-assessment',
                'action_name' => 'App\\Http\\Controllers\\ResultController@confirmAssessment',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            161 => 
            array (
                'id' => 162,
                'name' => 'hf.download-document',
                'method' => 'GET',
                'path' => 'hf/{id}/dataroom/download/{key}/{type?}',
                'action_name' => 'App\Http\Controllers\DocumentController@download',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            162 => 
            array (
                'id' => 163,
                'name' => 'admin.solar-installers.index',
                'method' => 'GET',
                'path' => 'admin/solar-installers',
                'action_name' => 'App\Http\Controllers\SolarInstallerController@index',
                'permission_id' => 187,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            161 => 
            array (
                'id' => 164,
                'name' => 'hf.datatable',
                'method' => 'GET',
                'path' => 'hf/{solar_installer_id}/datatable',
                'action_name' => 'App\Http\Controllers\HFController@dataTable',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            163 => 
            array (
                'id' => 165,
                'name' => 'user.favorite.projects.delete',
                'method' => 'GET',
                'path' => 'user/favorite/projects/{id}/delete',
                'action_name' => 'App\Http\Controllers\UserFavoriteController@destroyUserFavoriteProject',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            164 => 
            array (
                'id' => 166,
                'name' => 'user.favorite.projects.store',
                'method' => 'POST',
                'path' => 'user/favorite/projects/{id}',
                'action_name' => 'App\Http\Controllers\UserFavoriteController@storeUserFavoriteProject',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            165 => 
            array (
                'id' => 167,
                'name' => 'hf.confirm-create',
                'method' => 'GET',
                'path' => 'hf/confirm-create',
                'action_name' => 'App\\Http\\Controllers\\HFController@getModalCreate',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            166 => 
            array (
                'id' => 168,
                'name' => 'hf.create',
                'method' => 'POST',
                'path' => 'hf/create',
                'action_name' => 'App\\Http\\Controllers\\HFController@create',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            167 => 
            array (
                'id' => 169,
                'name' => 'user.project.list.view',
                'method' => 'POST',
                'path' => 'user/project/list/view',
                'action_name' => 'App\\Http\\Controllers\\UsersController@updateProjectListView',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            168 => 
            array (
                'id' => 170,
                'name' => 'hf.update-meta',
                'method' => 'POST',
                'path' => 'hf/{id}/update-meta',
                'action_name' => 'App\\Http\\Controllers\\ResultController@updateSiteMeta',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            169 => 
            array (
                'id' => 171,
                'name' => 'hf.datagrid',
                'method' => 'GET',
                'path' => 'hf/datagrid',
                'action_name' => 'App\\Http\\Controllers\\HFController@dataGrid',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:49:57',
                'enabled' => 1,
            ),
            170 => 
            array (
                'id' => 172,
                'name' => 'hf.submit-assessment',
                'method' => 'POST',
                'path' => 'hf/{id}/results',
                'action_name' => 'App\\Http\\Controllers\\ResultController@submitAssessment',
                'permission_id' => 175,
                'created_at' => '2016-07-20 20:45:25',
                'updated_at' => '2016-07-20 20:48:57',
                'enabled' => 1,
            ),
            171 => 
            array (
                'id' => 173,
                'name' => 'manufacturers.list',
                'method' => 'GET',
                'path' => 'globals/manufacturers',
                'action_name' => 'App\\Http\\Controllers\\ManufacturerController@index',
                'permission_id' => 0,
                'created_at' => '2016-07-20 20:45:26',
                'updated_at' => '2016-07-20 20:45:26',
                'enabled' => 1,
            ),
        ));
        
        
    }
}
